//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteProgramaTV.programacaotv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GuiaProgramacaoTVSoap", Namespace="http://guiaTv.org/")]
    public partial class GuiaProgramacaoTV : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CadastrarCanalOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarProgramaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodosCanaisOperationCompleted;

        internal void CadastrarPrograma(Programa programa)
        {
            throw new NotImplementedException();
        }

        private System.Threading.SendOrPostCallback TodaProgramacaoIdCanalOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodaProgramacaoPorDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback TodaProgramacaoIdCanalDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverCanalOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverProgramaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GuiaProgramacaoTV() {
            this.Url = global::ClienteProgramaTV.Properties.Settings.Default.ClienteProgramaTV_programacaotv_GuiaProgramacaoTV;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CadastrarCanalCompletedEventHandler CadastrarCanalCompleted;
        
        /// <remarks/>
        public event CadastrarProgramaCompletedEventHandler CadastrarProgramaCompleted;
        
        /// <remarks/>
        public event TodosCanaisCompletedEventHandler TodosCanaisCompleted;
        
        /// <remarks/>
        public event TodaProgramacaoIdCanalCompletedEventHandler TodaProgramacaoIdCanalCompleted;
        
        /// <remarks/>
        public event TodaProgramacaoPorDataCompletedEventHandler TodaProgramacaoPorDataCompleted;
        
        /// <remarks/>
        public event TodaProgramacaoIdCanalDataCompletedEventHandler TodaProgramacaoIdCanalDataCompleted;
        
        /// <remarks/>
        public event RemoverCanalCompletedEventHandler RemoverCanalCompleted;
        
        /// <remarks/>
        public event RemoverProgramaCompletedEventHandler RemoverProgramaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://guiaTv.org/CadastrarCanal", RequestNamespace="http://guiaTv.org/", ResponseNamespace="http://guiaTv.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Canal CadastrarCanal(Canal canal) {
            object[] results = this.Invoke("CadastrarCanal", new object[] {
                        canal});
            return ((Canal)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarCanalAsync(Canal canal) {
            this.CadastrarCanalAsync(canal, null);
        }
        
        /// <remarks/>
        public void CadastrarCanalAsync(Canal canal, object userState) {
            if ((this.CadastrarCanalOperationCompleted == null)) {
                this.CadastrarCanalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarCanalOperationCompleted);
            }
            this.InvokeAsync("CadastrarCanal", new object[] {
                        canal}, this.CadastrarCanalOperationCompleted, userState);
        }
        
        private void OnCadastrarCanalOperationCompleted(object arg) {
            if ((this.CadastrarCanalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarCanalCompleted(this, new CadastrarCanalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://guiaTv.org/CadastrarPrograma", RequestNamespace="http://guiaTv.org/", ResponseNamespace="http://guiaTv.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Programa CadastrarPrograma(Programa programa, int IdCanal) {
            object[] results = this.Invoke("CadastrarPrograma", new object[] {
                        programa,
                        IdCanal});
            return ((Programa)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarProgramaAsync(Programa programa, int IdCanal) {
            this.CadastrarProgramaAsync(programa, IdCanal, null);
        }
        
        /// <remarks/>
        public void CadastrarProgramaAsync(Programa programa, int IdCanal, object userState) {
            if ((this.CadastrarProgramaOperationCompleted == null)) {
                this.CadastrarProgramaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarProgramaOperationCompleted);
            }
            this.InvokeAsync("CadastrarPrograma", new object[] {
                        programa,
                        IdCanal}, this.CadastrarProgramaOperationCompleted, userState);
        }
        
        private void OnCadastrarProgramaOperationCompleted(object arg) {
            if ((this.CadastrarProgramaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarProgramaCompleted(this, new CadastrarProgramaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://guiaTv.org/TodosCanais", RequestNamespace="http://guiaTv.org/", ResponseNamespace="http://guiaTv.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Canal[] TodosCanais() {
            object[] results = this.Invoke("TodosCanais", new object[0]);
            return ((Canal[])(results[0]));
        }
        
        /// <remarks/>
        public void TodosCanaisAsync() {
            this.TodosCanaisAsync(null);
        }
        
        /// <remarks/>
        public void TodosCanaisAsync(object userState) {
            if ((this.TodosCanaisOperationCompleted == null)) {
                this.TodosCanaisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodosCanaisOperationCompleted);
            }
            this.InvokeAsync("TodosCanais", new object[0], this.TodosCanaisOperationCompleted, userState);
        }
        
        private void OnTodosCanaisOperationCompleted(object arg) {
            if ((this.TodosCanaisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodosCanaisCompleted(this, new TodosCanaisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://guiaTv.org/TodaProgramacaoIdCanal", RequestNamespace="http://guiaTv.org/", ResponseNamespace="http://guiaTv.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Programa[] TodaProgramacaoIdCanal(int IdCanal) {
            object[] results = this.Invoke("TodaProgramacaoIdCanal", new object[] {
                        IdCanal});
            return ((Programa[])(results[0]));
        }
        
        /// <remarks/>
        public void TodaProgramacaoIdCanalAsync(int IdCanal) {
            this.TodaProgramacaoIdCanalAsync(IdCanal, null);
        }
        
        /// <remarks/>
        public void TodaProgramacaoIdCanalAsync(int IdCanal, object userState) {
            if ((this.TodaProgramacaoIdCanalOperationCompleted == null)) {
                this.TodaProgramacaoIdCanalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodaProgramacaoIdCanalOperationCompleted);
            }
            this.InvokeAsync("TodaProgramacaoIdCanal", new object[] {
                        IdCanal}, this.TodaProgramacaoIdCanalOperationCompleted, userState);
        }
        
        private void OnTodaProgramacaoIdCanalOperationCompleted(object arg) {
            if ((this.TodaProgramacaoIdCanalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodaProgramacaoIdCanalCompleted(this, new TodaProgramacaoIdCanalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://guiaTv.org/TodaProgramacaoPorData", RequestNamespace="http://guiaTv.org/", ResponseNamespace="http://guiaTv.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Programa[] TodaProgramacaoPorData(System.DateTime data) {
            object[] results = this.Invoke("TodaProgramacaoPorData", new object[] {
                        data});
            return ((Programa[])(results[0]));
        }
        
        /// <remarks/>
        public void TodaProgramacaoPorDataAsync(System.DateTime data) {
            this.TodaProgramacaoPorDataAsync(data, null);
        }
        
        /// <remarks/>
        public void TodaProgramacaoPorDataAsync(System.DateTime data, object userState) {
            if ((this.TodaProgramacaoPorDataOperationCompleted == null)) {
                this.TodaProgramacaoPorDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodaProgramacaoPorDataOperationCompleted);
            }
            this.InvokeAsync("TodaProgramacaoPorData", new object[] {
                        data}, this.TodaProgramacaoPorDataOperationCompleted, userState);
        }
        
        private void OnTodaProgramacaoPorDataOperationCompleted(object arg) {
            if ((this.TodaProgramacaoPorDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodaProgramacaoPorDataCompleted(this, new TodaProgramacaoPorDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://guiaTv.org/TodaProgramacaoIdCanalData", RequestNamespace="http://guiaTv.org/", ResponseNamespace="http://guiaTv.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Programa[] TodaProgramacaoIdCanalData(int IdCanal, System.DateTime data) {
            object[] results = this.Invoke("TodaProgramacaoIdCanalData", new object[] {
                        IdCanal,
                        data});
            return ((Programa[])(results[0]));
        }
        
        /// <remarks/>
        public void TodaProgramacaoIdCanalDataAsync(int IdCanal, System.DateTime data) {
            this.TodaProgramacaoIdCanalDataAsync(IdCanal, data, null);
        }
        
        /// <remarks/>
        public void TodaProgramacaoIdCanalDataAsync(int IdCanal, System.DateTime data, object userState) {
            if ((this.TodaProgramacaoIdCanalDataOperationCompleted == null)) {
                this.TodaProgramacaoIdCanalDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodaProgramacaoIdCanalDataOperationCompleted);
            }
            this.InvokeAsync("TodaProgramacaoIdCanalData", new object[] {
                        IdCanal,
                        data}, this.TodaProgramacaoIdCanalDataOperationCompleted, userState);
        }
        
        private void OnTodaProgramacaoIdCanalDataOperationCompleted(object arg) {
            if ((this.TodaProgramacaoIdCanalDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodaProgramacaoIdCanalDataCompleted(this, new TodaProgramacaoIdCanalDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://guiaTv.org/RemoverCanal", RequestNamespace="http://guiaTv.org/", ResponseNamespace="http://guiaTv.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverCanal(int IdCanal) {
            this.Invoke("RemoverCanal", new object[] {
                        IdCanal});
        }
        
        /// <remarks/>
        public void RemoverCanalAsync(int IdCanal) {
            this.RemoverCanalAsync(IdCanal, null);
        }
        
        /// <remarks/>
        public void RemoverCanalAsync(int IdCanal, object userState) {
            if ((this.RemoverCanalOperationCompleted == null)) {
                this.RemoverCanalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverCanalOperationCompleted);
            }
            this.InvokeAsync("RemoverCanal", new object[] {
                        IdCanal}, this.RemoverCanalOperationCompleted, userState);
        }
        
        private void OnRemoverCanalOperationCompleted(object arg) {
            if ((this.RemoverCanalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverCanalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://guiaTv.org/RemoverPrograma", RequestNamespace="http://guiaTv.org/", ResponseNamespace="http://guiaTv.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverPrograma(int IdPrograma) {
            this.Invoke("RemoverPrograma", new object[] {
                        IdPrograma});
        }
        
        /// <remarks/>
        public void RemoverProgramaAsync(int IdPrograma) {
            this.RemoverProgramaAsync(IdPrograma, null);
        }
        
        /// <remarks/>
        public void RemoverProgramaAsync(int IdPrograma, object userState) {
            if ((this.RemoverProgramaOperationCompleted == null)) {
                this.RemoverProgramaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverProgramaOperationCompleted);
            }
            this.InvokeAsync("RemoverPrograma", new object[] {
                        IdPrograma}, this.RemoverProgramaOperationCompleted, userState);
        }
        
        private void OnRemoverProgramaOperationCompleted(object arg) {
            if ((this.RemoverProgramaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverProgramaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiaTv.org/")]
    public partial class Canal {
        
        private int idField;
        
        private string nomeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiaTv.org/")]
    public partial class Programa {
        
        private int idField;
        
        private string tituloField;
        
        private string descricaoField;
        
        private System.DateTime dataHoraField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataHora {
            get {
                return this.dataHoraField;
            }
            set {
                this.dataHoraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CadastrarCanalCompletedEventHandler(object sender, CadastrarCanalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarCanalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarCanalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Canal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Canal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CadastrarProgramaCompletedEventHandler(object sender, CadastrarProgramaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarProgramaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarProgramaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Programa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Programa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TodosCanaisCompletedEventHandler(object sender, TodosCanaisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodosCanaisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodosCanaisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Canal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Canal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TodaProgramacaoIdCanalCompletedEventHandler(object sender, TodaProgramacaoIdCanalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodaProgramacaoIdCanalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodaProgramacaoIdCanalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Programa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Programa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TodaProgramacaoPorDataCompletedEventHandler(object sender, TodaProgramacaoPorDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodaProgramacaoPorDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodaProgramacaoPorDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Programa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Programa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TodaProgramacaoIdCanalDataCompletedEventHandler(object sender, TodaProgramacaoIdCanalDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodaProgramacaoIdCanalDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodaProgramacaoIdCanalDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Programa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Programa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void RemoverCanalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void RemoverProgramaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591